# Generated by Django 4.2.6 on 2023-10-09 22:18

from django.db import migrations, models

def data_transfert(apps, schema_editor):
    OldTableProfile = apps.get_model('oc_lettings_site', 'profile')
    NewTableProfile = apps.get_model('profiles', 'profile2')

    data_to_transfert3 = OldTableProfile.objects.all()

    for data in data_to_transfert3:
        new_data = NewTableProfile()
        new_data.id = data.id
        new_data.favorite_city = data.favorite_city
        new_data.user_id = data.user_id
        new_data.save()

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_transfert),
    ]
