# Generated by Django 4.2.6 on 2023-10-09 22:16

from django.db import migrations, models

def data_transfert(apps, schema_editor):
    OldTableLetting = apps.get_model('oc_lettings_site', 'letting')
    NewTableLetting = apps.get_model('lettings', 'letting2')
    OldTableAddress = apps.get_model('oc_lettings_site', 'address')
    NewTableAddress = apps.get_model('lettings', 'address2')

    data_to_transfert1 = OldTableLetting.objects.all()
    data_to_transfert2 = OldTableAddress.objects.all()

    for data in data_to_transfert1:
        print("DATA", data)
        new_data = NewTableLetting()
        new_data.id = data.id
        new_data.title = data.title
        new_data.address_id = data.address_id
        new_data.save()

    for data in data_to_transfert2:
        print("DATA", data)
        new_data = NewTableAddress()
        new_data.id = data.id
        new_data.number = data.number
        new_data.street = data.street
        new_data.city = data.city
        new_data.state = data.state
        new_data.zip_code = data.zip_code
        new_data.country_iso_code = data.country_iso_code
        new_data.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_transfert),
    ]
