# Generated by Django 4.2.6 on 2023-10-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20231010_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address2',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Letting2',
            new_name='Letting',
        ),
        migrations.AlterModelTable(
            name='address',
            table='oc_lettings_site_address',
        ),
        migrations.AlterModelTable(
            name='letting',
            table='oc_lettings_site_letting',
        ),
    ]
