version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.5-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.03.1-ce
      - run:
          name: Build Docker Image
          command: docker build -t lechat76/projet13oc .
      - run:
          name: Run Tests with Pytest
          command: pytest --nomigrations --disable-warnings
  deploy:
    docker:
      - image: docker:20.10.5
    steps:
      - setup_remote_docker:
          version: 18.03.1-ce
      - run:
          name: Push Docker Image to Registry
          command: docker push lechat76/projet13oc
