version: 2.1 

orbs:
  docker: circleci/docker@2.1.3
  python: circleci/python@2.0.3
  render: circleci/render-orb@1.0.0

jobs:
  pytest:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: check test with Pytest
          command: pytest --nomigrations --disable-warnings
  flake8:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install Flake8
          command: pip install flake8==3.7.0
      - run:
          name: check linting with Flake8
          command: flake8

  build-push-docker:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command:
            docker build -t $DOCKER_IMAGE:latest .
      - run:
          name: Connect to Docker Hub
          command:
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
      - run:
          name: Push docker image
          command:
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE |
            docker push $DOCKER_IMAGE

  deploye-from-dockerhub-to-render:
    docker:
      - image: $DOCKER_IMAGE
    steps:
      - checkout
      - run:
          name: Render Login
          command: render login --email "$RENDER_USERNAME" --password "$RENDER_PASSWORD"
      - run:
          name: Deploy to Render
          command: render up -n projet13oc -d $DOCKER_IMAGE


workflows:
  version: 2
  run_tests_and_build_docker:
    jobs:
      - pytest
      - flake8
      - build-push-docker:
          filters:
            branches:
              only: master
          requires:
            - flake8
            - pytest
      - deploye-from-dockerhub-to-render:
          filters:
            branches:
              only: master
          requires:
            - build-push-docker
