version: 2.1

description: |
    "Build, test and deploy to DockerHub"

orbs:
  python: circleci/python@1.4.0
  docker: circleci/docker@1.6.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run Flake8 to check linting
          command: flake8
      - run:
          name: Run Tests with Pytest
          command: pytest --nomigrations --disable-warnings          

  # test:
  #   docker:
  #     - image: cimg/python:3.10.2
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run Tests with Pytest
  #         command: pytest --nomigrations --disable-warnings

  # lint:
  #   docker:
  #     - image: cimg/python:3.10.2
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run Flake8 to check linting
  #         command: flake8

  deploy:
    executor: docker/default
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_HUB_USER_ID/projet13oc .
      - run:
          name: Push Docker Image to Registry
          command: docker push lechat76/projet13oc

workflows:
  build-and-deploy:
    jobs:
      - build-and-test:
      - deploy:
          requires:
            - build-and-test
