version: 2.1

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Create a Python virtual environment
          command: python -m venv venv
      - run:
          name: Activate the Python virtual environment
          command: source venv/bin/activate
      - run:
          name: Install project dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests with Pytest
          command: pytest --nomigrations --disable-warnings

  lint:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Create a Python virtual environment
          command: python -m venv venv
      - run:
          name: Activate the Python virtual environment
          command: source venv/bin/activate
      - run:
          name: Install project dependencies
          command: pip install flake8==3.7.0
      - run:
          name: Run Flake8 to check linting
          command: flake8

  deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_HUB_USER_ID/projet13oc .
      - run:
          name: Push Docker Image to Registry
          command: docker push lechat76/projet13oc

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test:
      - lint:
      - deploy:
          requires:
            - test
            - lint