version: 2
jobs:
  build:
    docker:
      - image: python:3.11.5-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 24.0.6
      - run:
          name: Build Docker Image
          command: docker build -t lechat76/projet13oc .
      - run:
          name: Run Tests with Pytest
          command: pytest --nomigrations --disable-warnings
      - run:
          name: Push Docker Image to Registry
          command: |
            echo "Logging in to Docker Hub..."
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PASSWORD
            docker push lechat76/projet13oc
  deploy:
    docker:
      - image: docker:24.0.6
    steps:
      - setup_remote_docker:
          version: 24.0.6
      - run:
          name: Push Docker Image to Registry
          command: docker push lechat76/projet13oc
