version: 2.1 

orbs:
  docker: circleci/docker@2.1.3
  python: circleci/python@2.0.3
  # heroku: circleci/heroku@2.0.0

jobs:
  run-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: check test with Pytest
          command: pytest --nomigrations --disable-warnings
      - run:
          name: check linting with Flake8
          command: flake8

  build-push-docker:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command:
            docker build -t lechat76/projet13oc:latest .
      - run:
          name: Connect to Docker Hub
          command:
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
      - run:
          name: Push docker image
          command:
            docker tag lechat76/projet13oc lechat76/projet13oc |
            docker push lechat76/projet13oc

  # deploye-from-dockerhub-to-heroku:
  #   docker:
  #     - image: $DOCKER_HUB_USER_ID/$IMAGE_NAME:$CIRCLE_SHA1
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Main to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main


workflows:
  version: 2
  run_tests_and_build_docker:
    jobs:
      - run-test
      - build-push-docker:
          filters:
            branches:
              only: master
          requires:
            - run-test
      # - deploye-from-dockerhub-to-heroku:
      #     filters:
      #       branches:
      #         only: master
          requires:
            - build-push-docker
