version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: docker build -t lechat76/projet13oc .
      - run:
          name: Create a Python virtual environment
          command: python -m venv venv
      - run:
          name: Activate the Python virtual environment
          command: . venv/bin/activate
      - run:
          name: Install project dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests with Pytest
          command: pytest --nomigrations --disable-warnings
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
            docker push lechat76/projet13oc
  deploy:
    docker:
      - image: cimg/base:2022.06
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Push Docker Image to Registry
          command: docker push lechat76/projet13oc
